[Fix] Upgraded the packages with the latest version
RealDevSquad/react-tests-tdd pull request #56
Opened 2024-08-20 09:40 UTC by shubhdevelop

Added a dev Dependency as fallback, there was a
packages babel-preset-react-app that was importing @babel/plugin-proposal-private-property-in-object, but was present in node_module for some other purposes, it could cause break in future,

This was a bug as create-react-app is no longer being maintained, thus it was unlikely the bug was going to be fixed.

Date:  20 Aug 2024

Developer Name: Shubham Raj

---

## Issue Ticket Number

#55 

Update the package in the Repo to current latest version, ensuring there is no breaks, and all the dependencies are working fine. Tests are are working as intended.
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag
- [ ] Yes
- [x] No

### Database Changes
- [ ] Yes
- [x] No

- Dev server is also working fine
### Breaking Changes

- [x] Yes
- [ ] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Build Working</summary>

![image](https://github.com/user-attachments/assets/f9dd38d1-4f5b-4e41-8a12-16573241417c)

</details>

## Test Coverage
<details>
<summary>Test Coverage</summary>

![image](https://github.com/user-attachments/assets/207528ca-6d24-4a38-a217-a7f705420e82)

</details>

### Dev Server
<details>
<summary>Test Coverage</summary>
[Screencast from 20-08-24 03:06:05 PM IST.webm](https://github.com/user-attachments/assets/f04a11b0-5ad8-406d-9bfd-b0ea865ffe0c)

</details>

2024-08-20 18:17 UTC, akankshadharkar commented
Why does this PR add a component?

2024-08-20 19:28 UTC, iamitprakash requested changes

2024-08-20 19:28 UTC, iamitprakash commented on package.json
> +    "web-vitals": "^4.2.3"
can we remove ^ from all where

2024-08-20 19:30 UTC, shubhdevelop commented
> Why does this PR add a component?

App was breaking at the App.js while running tests, the component was imported but and no such component was found in index.js

2024-08-20 19:32 UTC, shubhdevelop commented on package.json
> +    "web-vitals": "^4.2.3"
okay

2024-08-20 19:39 UTC, iamitprakash approved these changes

2024-08-20 19:39 UTC, merged

2024-08-21 04:50 UTC, ankushdharkar reviewed
@iamitprakash @shubhdevelop There are issues in installing the packages after this PR. Please validate the changes next time before merging.

2024-08-21 04:50 UTC, ankushdharkar commented on package.json
> +    "t @testing-library/react": "16.0.0",
Is this name correct?

2024-08-21 04:50 UTC, ankushdharkar commented on package.json
> +    "@babel/plugin-proposal-private-property-in-object": "7.21.11"
Why do we need this?

2024-08-21 04:50 UTC, ankushdharkar commented on src/components/starbucks-input/StarbucksInput.js
> +export default function StartbucksInput() {
Typo in *Starbucks name

2024-08-21 04:50 UTC, ankushdharkar commented on src/components/starbucks-input/index.spec.js
> +import StarbucksInput from './StarbucksInput.js';
Going to comment this out and let people create the file in their tests :)